INPUT:
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  INPUT_SIZE: (224, 224)

MODEL:
  DEVICE: "cuda:0"
  ARCHITECTURE: "unet"
  USE_PERTRAINED_BACKBONE: True
  BACKBONE: "resnet34"
  OPTIMIZER: "adam"
  LOSS: "binary_crossentropy"

DATASETS:
  TRAIN: ('/isilon_yuval/Automotive/RnD/yuval.l/data/windshield_ds_new_chips-bulleye-windows/train')
  TEST: ('/isilon_yuval/Automotive/RnD/yuval.l/data/windshield_ds_new_chips-bulleye-windows/test')

OUTPUT_DIR: '/isilon_yuval/Automotive/RnD/yuval.l/models/unet-model-windshield/'
